import streamlit as st
import pandas as pd
import joblib

# Page setup
st.set_page_config(
    page_title="Credit Scoring Demo",
    page_icon="💳",
    layout="centered"
)

# Load saved model and training columns
try:
    model = joblib.load("credit_scoring_model.pkl")
    feature_columns = joblib.load("feature_columns.pkl")
except FileNotFoundError:
    st.error(
        "Model files are missing. Run main.py first to train and save "
        "the model and feature columns."
    )
    st.stop()

# App heading
st.title("💳 Credit Scoring Model")
st.write(
    "Enter applicant details below to see the model's estimated "
    "credit default risk."
)

st.info(
    "Educational project demo only. This is not a real lending decision "
    "or financial advice."
)

# Applicant input form
st.subheader("Applicant details")

with st.form("applicant_form"):
    age = st.number_input(
        "Age",
        min_value=18,
        max_value=100,
        value=25,
        step=1
    )

    income = st.number_input(
        "Annual income",
        min_value=0,
        value=50000,
        step=1000
    )

    home = st.selectbox(
        "Home ownership",
        ["RENT", "OWN", "MORTGAGE", "OTHER"]
    )

    employment_years = st.number_input(
        "Years employed",
        min_value=0.0,
        max_value=60.0,
        value=2.0,
        step=0.5
    )

    loan_intent = st.selectbox(
        "Loan purpose",
        [
            "PERSONAL",
            "EDUCATION",
            "MEDICAL",
            "VENTURE",
            "HOMEIMPROVEMENT",
            "DEBTCONSOLIDATION"
        ]
    )

    loan_grade = st.selectbox(
        "Loan grade",
        ["A", "B", "C", "D", "E", "F", "G"]
    )

    loan_amount = st.number_input(
        "Loan amount",
        min_value=0,
        value=5000,
        step=500
    )

    interest_rate = st.number_input(
        "Loan interest rate (%)",
        min_value=0.0,
        max_value=100.0,
        value=10.0,
        step=0.5
    )

    previous_default = st.selectbox(
        "Previous default on file?",
        ["N", "Y"]
    )

    credit_history_years = st.number_input(
        "Credit history length (years)",
        min_value=0.0,
        max_value=60.0,
        value=3.0,
        step=0.5
    )

    submitted = st.form_submit_button("Predict credit risk")

# Run prediction when the form is submitted
if submitted:
    if income <= 0:
        st.warning("Please enter an annual income greater than zero.")
    else:
        # Calculate loan amount as a fraction of annual income
        loan_percent_income = loan_amount / income

        # Create one applicant row using the dataset's original column names
        applicant = pd.DataFrame([{
            "person_age": age,
            "person_income": income,
            "person_home_ownership": home,
            "person_emp_length": employment_years,
            "loan_intent": loan_intent,
            "loan_grade": loan_grade,
            "loan_amnt": loan_amount,
            "loan_int_rate": interest_rate,
            "loan_percent_income": loan_percent_income,
            "cb_person_default_on_file": previous_default,
            "cb_person_cred_hist_length": credit_history_years
        }])

        # Encode categorical values as during training
        applicant = pd.get_dummies(applicant, drop_first=True)

        # Match the exact training feature columns and their order
        applicant = applicant.reindex(
            columns=feature_columns,
            fill_value=0
        )

        # Predict class and estimate default probability
        prediction = model.predict(applicant)[0]
        probabilities = model.predict_proba(applicant)[0]

        default_class_index = list(model.classes_).index(1)
        default_probability = probabilities[default_class_index]

        st.subheader("Prediction result")

        if prediction == 1:
            st.error("Model prediction: Default")
        else:
            st.success("Model prediction: No default")

        st.metric(
            "Estimated default probability",
            f"{default_probability:.1%}"
        )

        st.caption(
            "This result is generated by a student machine-learning model "
            "and should not be used to approve or reject a real loan."
        )